name: Petclinic UI tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with: 
        node-version: '14'
    - uses: microsoft/playwright-github-action@v1

    - name: Install dependencies
      run:  npm i && npx playwright install

    - name: Run Playwright tests
      run: npx playwright test

    - name: Publish HTML report
      if: always()
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: playwright-report
        keep_files: true 
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'